### ISSUE TITLE
Türme können ineinander platziert werden

### ISSUE THREAD

**Issue by RobinOppitz** [LoudenOMP/AutoDefense#15]
Beschreibung: Man kann einen Turm auf einen anderen Turm und außerhalb der Map platzieren und diese unendlich stacken.
Expectet Result: Türme können nur nebeneinander, auf der Map platziert werden.
Actual Result: Türme können ineinander, außerhalb der Map platziert werden.
Steps to Reproduce: platziere einen Turm auf einen anderen/außerhalb der Map.
Priority: Minor?

![Unbenannt](https://user-images.githubusercontent.com/97678875/156185462-141d9ebd-97c5-4af8-91bd-8355b6c7203f.PNG)

**Comment by LoudenOMP** [comment]
Danke dir für diesen Report! Das Problem wurde behoben!
